title: "Pique"
timezone: UTC
baseurl: ""
permalink: "/:title/"
logo: 'assets/images/pique_logo.png'
favicon: 'assets/images/pique_favicon.ico'
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true
sass:
  sass_dir: _sass
  style: :compressed
# ganalytics: UA-113961478-1

# Plugins
plugins: 
- jekyll-paginate
- jekyll-sitemap
- jekyll-feed
- jekyll-seo-tag
- jekyll-archives